version: "3"

services:
  db:
    image: postgres:9.4-alpine
    volumes:
      - ~/.ggpet/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ggpet_development
  redis:
    image: redis:3.2-alpine
    volumes:
      - ~/.ggpet/redis:/data
    ports:
      - 6379:6379
